template: templates/loz-script-project.yaml
overrides:
  artifacts:
    - type: script
      build_script:
        gh_name: elasticsearch
        repo_name: linux-on-ibm-z-scripts
        path: src/build.sh
        args: --version 9.0.2
        docker_image: zlinux-artifacts-builder
